
name: simo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0
  go_router: ^14.6.3
  get_it: ^8.0.3
  dartz: ^0.10.1
  freezed_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  image_picker: ^1.0.0
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  freezed: ^3.0.0
  riverpod_generator: ^2.6.5
  riverpod_annotation: ^2.6.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imagenes/logo_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/imagenes/opciones/
    - assets/imagenes/canjear/
    - assets/imagenes/busqueda/
    - assets/imagenes/usuario/
    - assets/imagenes/usuario/editar_usuario/

